<?xml version="1.0" encoding="utf-8"?><Database Name="UTop" Class="DataTypeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Localhost;Initial Catalog=Utop_New;User ID=sa" SettingsObjectName="StartUp.Properties.Settings" SettingsPropertyName="UTopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Groups_Users" Member="Groups" ThisKey="Type" OtherKey="Type" Type="Groups" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.root" Member="root">
    <Type Name="root">
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Groups" Member="Groups">
    <Type Name="Groups">
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Test" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Build" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Manage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HWDebug" Member="Query" Storage="_HWDebug" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Groups_Users" Member="Users" ThisKey="Type" OtherKey="Type" Type="Users" />
    </Type>
  </Table>
</Database>